Include bzl dependency files in release package
Bumping to `0.60.0` and trying to run `bazel test "@SwiftLint//Tests:ExtraRulesTests"` revealed the issue
```
ERROR: error loading package '@@swiftlint~//Tests': cannot load '@@swiftlint~//Tests:generated_tests.bzl': no such file
```

as these files aren't packaged into the release. I went ahead and added them as a part of the release package but let me know if there's a better approach instead.