Proof of concept for custom native rules without Bazel
To try this out, run this locally:

```swift
$ swift run -c release swiftlint --progress
...
Linting Swift files in current working directory
592 of 592 [==============================] ETA: 0s (318 files/s)
/Users/jp/src/SwiftLint/Source/swiftlint/Commands/SwiftLint.swift:12:13: error: Plugin Example Rule Violation: Identifiers cannot be named 'forbidden' (plugin_example)
Done linting! Found 1 violation, 1 serious in 592 files.
```

Or to develop the custom rules in Xcode:

```swift
swift run -c release swiftlint dev
```

We might never be able to ship a compelling version of this, but I
thought I'd share some of my explorations for supporting SwiftLint
"plugins" that would, among other things, enable users to write their
own native rules built on SwiftSyntax or anything else.

There's some massive downsides to this strategy that I'm not sure have
good solutions:

1. This approach doesn't work on Linux (actually it might, but some
   stuff might not work)
2. This approach requires building SwiftSyntax from source with release
   optimizations, which takes multiple minutes. Even if this is cached
   locally, on the first run this is going to be extremely slow, which
   would also severely impact CI jobs.
3. We've been chipping away at the need to have a Swift compiler
   toolchain installed by migrating our rules to be based on SwiftSyntax
   so eventually won't need SourceKit, but if we go down this route,
   we'll definitely need a Swift toolchain to be installed on the target
   machine.