Include `.bzl` dependency files in release package (#6225)
Bumping to `0.60.0` and trying to run `bazel test "@SwiftLint//Tests:ExtraRulesTests"` revealed the issue:
```
ERROR: error loading package '@@swiftlint~//Tests': cannot load '@@swiftlint~//Tests:generated_tests.bzl': no such file
```